// Get JasonPlaceHolder
export const GET_JASONPLACEHOLDER_REQUEST = 'GET_JASONPLACEHOLDER_REQUEST';
export const GET_JASONPLACEHOLDER_SUCCESS = 'GET_JASONPLACEHOLDER_SUCCESS';
export const GET_JASONPLACEHOLDER_FAILURE = 'GET_JASONPLACEHOLDER_FAILURE';